# Generated by Django 4.0.3 on 2022-03-12 12:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A short description of the article', max_length=75, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Details about the article', verbose_name='description')),
                ('publish_date', models.DateField(default=datetime.datetime.now, help_text='The date and time the article was published')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='The name of the author', max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, help_text='The date this change was made', verbose_name='when')),
                ('modelname', models.CharField(help_text='The model to which this change applies', max_length=50, verbose_name='model')),
                ('objectid', models.BigIntegerField(blank=True, help_text='The id of the record that was changed', null=True, verbose_name='object id')),
                ('fieldname', models.CharField(help_text='The that was changed', max_length=50, verbose_name='field')),
                ('old_value', models.TextField(blank=True, help_text='The value of the field before the change', null=True, verbose_name='old value')),
                ('new_value', models.TextField(blank=True, help_text='The value of the field after the change', verbose_name='new value')),
                ('user', models.ForeignKey(help_text='The user who made this change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flaxarticle_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-when', 'modelname', 'objectid'),
            },
        ),
        migrations.CreateModel(
            name='ArticleNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, help_text='The text of the note', max_length=255, verbose_name='text')),
                ('when', models.DateTimeField(default=datetime.datetime.now, help_text='The date that the note was submitted', verbose_name='when')),
                ('article', models.ForeignKey(help_text='The article to which this note applies', on_delete=django.db.models.deletion.CASCADE, to='flaxarticles.article')),
                ('submitted_by', models.ForeignKey(help_text='The author who submitted this note', null=True, on_delete=django.db.models.deletion.SET_NULL, to='flaxarticles.author', verbose_name='submitted by')),
            ],
            options={
                'ordering': ['-when'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, help_text='The author primarily responsible for executing this article', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_responsibility', to='flaxarticles.author', verbose_name='author'),
        ),
    ]
