# Generated by Django 4.0.3 on 2022-03-13 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flaxarticles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(help_text='The article to which this note applies', on_delete=django.db.models.deletion.CASCADE, to='flaxarticles.article')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='EnteredText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='The title of the link (may be the same or different from the article to which it is attached)', max_length=255, verbose_name='title')),
                ('text', models.TextField(help_text='The entered text', verbose_name='text')),
                ('anchor', models.ForeignKey(help_text='The anchor point of the article to which this file is attached', null=True, on_delete=django.db.models.deletion.SET_NULL, to='flaxarticles.documentanchor')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='The title of the link (may be the same or different from the article to which it is attached)', max_length=255, verbose_name='title')),
                ('href', models.URLField(help_text='The url of the link', verbose_name='url')),
                ('anchor', models.ForeignKey(help_text='The anchor point of the article to which this file is attached', null=True, on_delete=django.db.models.deletion.SET_NULL, to='flaxarticles.documentanchor')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='The title of the document (may be the same or different from the article to which it is attached)', max_length=255, verbose_name='title')),
                ('upload_date', models.DateField(auto_now=True, verbose_name='Date Uploaded')),
                ('file', models.FileField(help_text='The uploaded file', upload_to='', verbose_name='file')),
                ('anchor', models.ForeignKey(help_text='The anchor point of the article to which this file is attached', null=True, on_delete=django.db.models.deletion.SET_NULL, to='flaxarticles.documentanchor')),
            ],
            options={
                'ordering': ['upload_date'],
            },
        ),
        migrations.DeleteModel(
            name='ArticleNote',
        ),
    ]
