# Generated by Django 4.0.3 on 2022-03-13 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flaxarticles', '0002_documentanchor_enteredtext_link_uploadedfile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentanchor',
            options={'ordering': ['id']},
        ),
    ]
