# Generated by Django 4.0.3 on 2022-03-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flaxarticles', '0004_tag_alter_author_options_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(blank=True, help_text='The author or authors of this article', related_name='article_responsibility', to='flaxarticles.author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='The tags to which the article belongs', to='flaxarticles.tag'),
        ),
    ]
