# Generated by Django 4.0.3 on 2022-03-13 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flaxarticles', '0005_remove_article_author_article_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1000, help_text='The order in which this author is displayed in the credits for the article (default set very high)', verbose_name='order')),
            ],
            options={
                'ordering': ['article', 'order', 'author'],
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(blank=True, help_text='The author or authors of this article', related_name='article_responsibility', through='flaxarticles.Authorship', to='flaxarticles.author'),
        ),
        migrations.AddField(
            model_name='authorship',
            name='article',
            field=models.ForeignKey(help_text='The article', on_delete=django.db.models.deletion.CASCADE, to='flaxarticles.article'),
        ),
        migrations.AddField(
            model_name='authorship',
            name='author',
            field=models.ForeignKey(help_text='The author of the article', on_delete=django.db.models.deletion.CASCADE, to='flaxarticles.author'),
        ),
    ]
